services:
  postgres:
    image: postgres:16-alpine
    container_name: capputeeno_auth_postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - capputeeno_auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U henry -d capputeeno_auth"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  capputeeno_auth_pgdata: